In [113]:
import pandas as pd
pd.set_option('display.max_rows', 500)
from sklearn.preprocessing import OrdinalEncoder
from pathlib import Path

In [114]:
datafile_path = Path(r'.\datasets\fake_dataset_csv.csv')

In [115]:
df = pd.read_csv(datafile_path)

In [116]:
df.head()

,course_id,topic_id,topic_title,entry_id,Semester and Year,entry_message,entry_word_count,reply_id,reply_message,reply_word_count
0,9999999,1111111,Week 0: Introductions (Section Z),Ryan Bullock,Fall 2019,Type when in hand or question offer. Leonora C...,904,Kristopher Jones,Successful citizen discussion marriage candida...,175
1,9999999,1111111,Week 0: Introductions (Section Z),Andrew Roy,Fall 2019,Assume animal art south nature perform throw k...,385,Chad Young,That use mission recently resource. Dino Buzzati,733
2,9999999,1111111,Week 0: Introductions (Section Z),Tina Mckay,Spring 2020,Anyone role technology benefit list right thou...,519,Diana Young,Approach style him understand. Leonora Carrington,185
3,9999999,1111111,Week 0: Introductions (Section Z),Vicki Robertson,Fall 2022,Tv although service three kitchen while work p...,383,Debra Martin,Page city history involve painting. Leonora Ca...,264
4,9999999,1111111,Week 0: Introductions (Section Z),Joy Hernandez,Fall 2021,Simply mean local consumer financial discuss. ...,465,Scott Powell,Lead sport drop hour shoulder. Leonora Carrington,623

In [117]:
ord_enc = OrdinalEncoder()
df['entry_id'] = ord_enc.fit_transform(df[['entry_id']]).astype('int')
df['reply_id'] = ord_enc.fit_transform(df[['reply_id']]).astype('int')
df.head(10)

,course_id,topic_id,topic_title,entry_id,Semester and Year,entry_message,entry_word_count,reply_id,reply_message,reply_word_count
0,9999999,1111111,Week 0: Introductions (Section Z),82,Fall 2019,Type when in hand or question offer. Leonora C...,904,59,Successful citizen discussion marriage candida...,175
1,9999999,1111111,Week 0: Introductions (Section Z),6,Fall 2019,Assume animal art south nature perform throw k...,385,13,That use mission recently resource. Dino Buzzati,733
2,9999999,1111111,Week 0: Introductions (Section Z),95,Spring 2020,Anyone role technology benefit list right thou...,519,23,Approach style him understand. Leonora Carrington,185
3,9999999,1111111,Week 0: Introductions (Section Z),98,Fall 2022,Tv although service three kitchen while work p...,383,21,Page city history involve painting. Leonora Ca...,264
4,9999999,1111111,Week 0: Introductions (Section Z),46,Fall 2021,Simply mean local consumer financial discuss. ...,465,88,Lead sport drop hour shoulder. Leonora Carrington,623
5,9999999,1111111,Week 0: Introductions (Section Z),65,Spring 2022,Defense part red describe traditional enough a...,606,87,South order result report. William Sansom,663
6,9999999,1111111,Week 0: Introductions (Section Z),91,Fall 2022,Money book station yard across medical hundred...,920,86,Serious debate light city decide church. Steph...,471
7,9999999,1111111,Week 0: Introductions (Section Z),58,Fall 2020,Arm create bad foreign bill skill school one u...,170,61,Audience tonight evening mean. Stephen King,921
8,9999999,1111111,Week 0: Introductions (Section Z),52,Fall 2020,Least house special court space half trial bil...,607,93,Just produce beat phone not air. Jeff VanderMeer,126
9,9999999,1111111,Week 0: Introductions (Section Z),25,Spring 2021,Evening employee Mrs artist end billion space ...,665,49,Change various investment better well. Stephen...,698

In [120]:
from author_names import author_Names

def author_extraction(string):
    authorMentions = {}
    for author in author_Names:
        aliases = author_Names[author]
        for alias in aliases:
            if alias in string:
                authorMentions[author] = alias
    return authorMentions

df['extracted'] = df['entry_message'].apply(author_extraction)
df['extracted_from_replies'] = df['reply_message'].apply(author_extraction)
print(df.head())

   course_id  topic_id                        topic_title  entry_id  \
0    9999999   1111111  Week 0: Introductions (Section Z)        82
1    9999999   1111111  Week 0: Introductions (Section Z)         6
2    9999999   1111111  Week 0: Introductions (Section Z)        95
3    9999999   1111111  Week 0: Introductions (Section Z)        98
4    9999999   1111111  Week 0: Introductions (Section Z)        46

  Semester and Year                                      entry_message  \
0         Fall 2019  Type when in hand or question offer. Leonora C...
1         Fall 2019  Assume animal art south nature perform throw k...
2       Spring 2020  Anyone role technology benefit list right thou...
3         Fall 2022  Tv although service three kitchen while work p...
4         Fall 2021  Simply mean local consumer financial discuss. ...

   entry_word_count  reply_id  \
0               904        59
1               385        13
2               519        23
3               383        21
4               465        88

                                       reply_message  reply_word_count  \
0  Successful citizen discussion marriage candida...               175
1   That use mission recently resource. Dino Buzzati               733
2  Approach style him understand. Leonora Carrington               185
3  Page city history involve painting. Leonora Ca...               264
4  Lead sport drop hour shoulder. Leonora Carrington               623

                              extracted                extracted_from_replies
0                    {34: 'Carrington'}  {4: 'VanderMeer', 102: 'VanderMeer'}
1                                    {}                                    {}
2                          {91: 'King'}                    {34: 'Carrington'}
3                                    {}                    {34: 'Carrington'}
4  {4: 'VanderMeer', 102: 'VanderMeer'}                    {34: 'Carrington'}

In [121]:
def convert_dict(dictionary):
    list_of_keys = list(dictionary.keys())
    return(list_of_keys)

df['target'] = df['extracted'].apply(convert_dict)

In [122]:
posts_for_explode = df.copy()
df_exploded = posts_for_explode.explode('target')
#print(df_exploded.columns)
print(df_exploded.head())

   course_id  topic_id                        topic_title  entry_id  \
0    9999999   1111111  Week 0: Introductions (Section Z)        82
1    9999999   1111111  Week 0: Introductions (Section Z)         6
2    9999999   1111111  Week 0: Introductions (Section Z)        95
3    9999999   1111111  Week 0: Introductions (Section Z)        98
4    9999999   1111111  Week 0: Introductions (Section Z)        46

  Semester and Year                                      entry_message  \
0         Fall 2019  Type when in hand or question offer. Leonora C...
1         Fall 2019  Assume animal art south nature perform throw k...
2       Spring 2020  Anyone role technology benefit list right thou...
3         Fall 2022  Tv although service three kitchen while work p...
4         Fall 2021  Simply mean local consumer financial discuss. ...

   entry_word_count  reply_id  \
0               904        59
1               385        13
2               519        23
3               383        21
4               465        88

                                       reply_message  reply_word_count  \
0  Successful citizen discussion marriage candida...               175
1   That use mission recently resource. Dino Buzzati               733
2  Approach style him understand. Leonora Carrington               185
3  Page city history involve painting. Leonora Ca...               264
4  Lead sport drop hour shoulder. Leonora Carrington               623

                              extracted                extracted_from_replies  \
0                    {34: 'Carrington'}  {4: 'VanderMeer', 102: 'VanderMeer'}
1                                    {}                                    {}
2                          {91: 'King'}                    {34: 'Carrington'}
3                                    {}                    {34: 'Carrington'}
4  {4: 'VanderMeer', 102: 'VanderMeer'}                    {34: 'Carrington'}

  target
0     34
1    NaN
2     91
3    NaN
4      4

In [124]:
cols_to_keep = ['topic_title', 'entry_id', 'reply_id', 'Semester and Year']

In [127]:
df_student_to_student = df_exploded[cols_to_keep]
df_exploded_dropped = df_exploded.drop(['entry_message', 'entry_word_count', 'reply_word_count', 'extracted', 'extracted_from_replies', 'reply_message'], axis=1)

In [128]:
frames = [df_student_to_student, df_exploded_dropped]

In [130]:
all_together = pd.concat(frames)
all_together.drop_duplicates()
all_together.dropna(subset=['target'])

,topic_title,entry_id,reply_id,Semester and Year,course_id,topic_id,target
0,Week 0: Introductions (Section Z),82,59,Fall 2019,9999999.0,1111111.0,34
2,Week 0: Introductions (Section Z),95,23,Spring 2020,9999999.0,1111111.0,91
4,Week 0: Introductions (Section Z),46,88,Fall 2021,9999999.0,1111111.0,4
4,Week 0: Introductions (Section Z),46,88,Fall 2021,9999999.0,1111111.0,102
5,Week 0: Introductions (Section Z),65,87,Spring 2022,9999999.0,1111111.0,34
6,Week 0: Introductions (Section Z),91,86,Fall 2022,9999999.0,1111111.0,4
6,Week 0: Introductions (Section Z),91,86,Fall 2022,9999999.0,1111111.0,102
12,Week 0: Introductions (Section Z),76,15,Spring 2022,9999999.0,1111111.0,4
12,Week 0: Introductions (Section Z),76,15,Spring 2022,9999999.0,1111111.0,102
13,Week 0: Introductions (Section Z),73,41,Spring 2021,9999999.0,1111111.0,91
15,Week 0: Introductions (Section Z),84,98,Spring 2022,9999999.0,1111111.0,34
16,Week 0: Introductions (Section Z),13,81,Fall 2020,9999999.0,1111111.0,4
16,Week 0: Introductions (Section Z),13,81,Fall 2020,9999999.0,1111111.0,102
17,Week 0: Introductions (Section Z),44,83,Spring 2022,9999999.0,1111111.0,91
18,Week 0: Introductions (Section Z),34,36,Spring 2021,9999999.0,1111111.0,34
19,Week 0: Introductions (Section Z),71,69,Spring 2019,9999999.0,1111111.0,4
19,Week 0: Introductions (Section Z),71,69,Spring 2019,9999999.0,1111111.0,102
20,Week 0: Introductions (Section Z),72,72,Fall 2019,9999999.0,1111111.0,4
20,Week 0: Introductions (Section Z),72,72,Fall 2019,9999999.0,1111111.0,102
21,Week 0: Introductions (Section Z),40,50,Fall 2019,9999999.0,1111111.0,4
21,Week 0: Introductions (Section Z),40,50,Fall 2019,9999999.0,1111111.0,102
22,Week 0: Introductions (Section Z),70,71,Fall 2022,9999999.0,1111111.0,91
25,Week 0: Introductions (Section Z),27,26,Spring 2022,9999999.0,1111111.0,34
29,Week 0: Introductions (Section Z),29,30,Fall 2021,9999999.0,1111111.0,4
29,Week 0: Introductions (Section Z),29,30,Fall 2021,9999999.0,1111111.0,102
30,Week 0: Introductions (Section Z),51,12,Spring 2021,9999999.0,1111111.0,4
30,Week 0: Introductions (Section Z),51,12,Spring 2021,9999999.0,1111111.0,102
31,Week 0: Introductions (Section Z),31,18,Spring 2020,9999999.0,1111111.0,4
31,Week 0: Introductions (Section Z),31,18,Spring 2020,9999999.0,1111111.0,102
32,Week 0: Introductions (Section Z),10,7,Fall 2020,9999999.0,1111111.0,4
32,Week 0: Introductions (Section Z),10,7,Fall 2020,9999999.0,1111111.0,102
37,Week 0: Introductions (Section Z),57,67,Fall 2020,9999999.0,1111111.0,34
38,Week 0: Introductions (Section Z),93,48,Spring 2021,9999999.0,1111111.0,4
38,Week 0: Introductions (Section Z),93,48,Spring 2021,9999999.0,1111111.0,102
39,Week 0: Introductions (Section Z),66,6,Fall 2020,9999999.0,1111111.0,91
40,Week 0: Introductions (Section Z),86,45,Spring 2021,9999999.0,1111111.0,34
41,Week 0: Introductions (Section Z),0,28,Spring 2020,9999999.0,1111111.0,34
42,Week 0: Introductions (Section Z),96,74,Spring 2020,9999999.0,1111111.0,34
46,Week 0: Introductions (Section Z),16,53,Spring 2020,9999999.0,1111111.0,34
48,Week 0: Introductions (Section Z),55,60,Fall 2021,9999999.0,1111111.0,91
49,Week 0: Introductions (Section Z),83,56,Spring 2022,9999999.0,1111111.0,4
49,Week 0: Introductions (Section Z),83,56,Spring 2022,9999999.0,1111111.0,102
50,Week 0: Introductions (Section Z),69,54,Spring 2022,9999999.0,1111111.0,91
51,Week 0: Introductions (Section Z),19,78,Fall 2019,9999999.0,1111111.0,34
53,Week 0: Introductions (Section Z),64,3,Spring 2020,9999999.0,1111111.0,4
53,Week 0: Introductions (Section Z),64,3,Spring 2020,9999999.0,1111111.0,102
55,Week 0: Introductions (Section Z),87,16,Fall 2020,9999999.0,1111111.0,34
57,Week 0: Introductions (Section Z),94,5,Fall 2019,9999999.0,1111111.0,91
59,Week 0: Introductions (Section Z),63,24,Fall 2022,9999999.0,1111111.0,34
60,Week 0: Introductions (Section Z),92,92,Fall 2021,9999999.0,1111111.0,34
61,Week 0: Introductions (Section Z),45,66,Spring 2019,9999999.0,1111111.0,4
61,Week 0: Introductions (Section Z),45,66,Spring 2019,9999999.0,1111111.0,102
63,Week 0: Introductions (Section Z),78,8,Spring 2021,9999999.0,1111111.0,4
63,Week 0: Introductions (Section Z),78,8,Spring 2021,9999999.0,1111111.0,102
66,Week 0: Introductions (Section Z),59,51,Fall 2019,9999999.0,1111111.0,34
67,Week 0: Introductions (Section Z),47,17,Fall 2020,9999999.0,1111111.0,91
68,Week 0: Introductions (Section Z),41,94,Spring 2019,9999999.0,1111111.0,4
68,Week 0: Introductions (Section Z),41,94,Spring 2019,9999999.0,1111111.0,102
70,Week 0: Introductions (Section Z),89,46,Spring 2020,9999999.0,1111111.0,34
71,Week 0: Introductions (Section Z),18,70,Spring 2022,9999999.0,1111111.0,91
74,Week 0: Introductions (Section Z),53,76,Fall 2019,9999999.0,1111111.0,4
74,Week 0: Introductions (Section Z),53,76,Fall 2019,9999999.0,1111111.0,102
76,Week 0: Introductions (Section Z),26,65,Fall 2019,9999999.0,1111111.0,4
76,Week 0: Introductions (Section Z),26,65,Fall 2019,9999999.0,1111111.0,102
77,Week 0: Introductions (Section Z),21,29,Fall 2021,9999999.0,1111111.0,4
77,Week 0: Introductions (Section Z),21,29,Fall 2021,9999999.0,1111111.0,102
78,Week 0: Introductions (Section Z),48,73,Fall 2020,9999999.0,1111111.0,4
78,Week 0: Introductions (Section Z),48,73,Fall 2020,9999999.0,1111111.0,102
80,Week 0: Introductions (Section Z),42,40,Spring 2021,9999999.0,1111111.0,4
80,Week 0: Introductions (Section Z),42,40,Spring 2021,9999999.0,1111111.0,102
81,Week 0: Introductions (Section Z),60,22,Spring 2022,9999999.0,1111111.0,91
82,Week 0: Introductions (Section Z),33,20,Spring 2022,9999999.0,1111111.0,34
83,Week 0: Introductions (Section Z),9,42,Fall 2020,9999999.0,1111111.0,4
83,Week 0: Introductions (Section Z),9,42,Fall 2020,9999999.0,1111111.0,102
84,Week 0: Introductions (Section Z),28,58,Spring 2021,9999999.0,1111111.0,91
88,Week 0: Introductions (Section Z),14,95,Spring 2022,9999999.0,1111111.0,91
89,Week 0: Introductions (Section Z),38,84,Spring 2019,9999999.0,1111111.0,34
90,Week 0: Introductions (Section Z),1,82,Spring 2022,9999999.0,1111111.0,4
90,Week 0: Introductions (Section Z),1,82,Spring 2022,9999999.0,1111111.0,102
92,Week 0: Introductions (Section Z),20,27,Fall 2020,9999999.0,1111111.0,34
93,Week 0: Introductions (Section Z),99,1,Spring 2019,9999999.0,1111111.0,34
94,Week 0: Introductions (Section Z),43,85,Fall 2022,9999999.0,1111111.0,4
94,Week 0: Introductions (Section Z),43,85,Fall 2022,9999999.0,1111111.0,102
96,Week 0: Introductions (Section Z),39,80,Fall 2019,9999999.0,1111111.0,4
96,Week 0: Introductions (Section Z),39,80,Fall 2019,9999999.0,1111111.0,102
98,Week 0: Introductions (Section Z),30,47,Spring 2019,9999999.0,1111111.0,34